Feature/non lr parse#10
iijung/minishell pull request #30
Opened 2023-05-09 00:18 UTC by CodyKat

non_lr_parse mean "recursive downward parse"

내부에서 체크하는 syntax_error : 
1. &&, ||, | 의 잘못된 위치 에러
2. 괄호와 Dquote의 짝매칭

TODO : 
 1. 리다이렉션 위치와 짝이 맞는지 syntax체크
 2. 파스트리를 t_pipex에 파싱
 3. norm맞추기

![File](https://user-images.githubusercontent.com/98837511/236668411-ff5d678c-704a-44ae-9237-7845178981f4.jpg)

2023-05-09 17:21 UTC, iijung requested changes

2023-05-09 17:21 UTC, iijung commented on src/parse/parse_subshell.c
> +		*tmp_node = (*tmp_node)->next;
테스트 입력값 : `ls | ls | echo hi | test && (<< END cat)`

- 86번째 줄에서 *tmp_node를 할당 해제한 뒤 
- 87번째 줄에서(*tmp_node)->next 로 접근하고 있어서 세그폴트 발생되는 것으로 예상됨

```shell
==10922== Invalid read of size 8
==10922==    at 0x4035AD: subshell_parse_process (parse_subshell.c:87)
==10922==    by 0x4035AD: subshell_parse (parse_subshell.c:118)
==10922==    by 0x403871: operator_parse (parse_operator.c:96)
==10922==    by 0x403474: parse (parse.c:91)
==10922==    by 0x401394: run (minishell.c:29)
==10922==    by 0x401394: main (minishell.c:62)
==10922==  Address 0x4b3a498 is 8 bytes inside a block of size 16 free'd
==10922==    at 0x483CA3F: free (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==10922==    by 0x4035AC: subshell_parse_process (parse_subshell.c:86)
==10922==    by 0x4035AC: subshell_parse (parse_subshell.c:118)
==10922==    by 0x403871: operator_parse (parse_operator.c:96)
==10922==    by 0x403474: parse (parse.c:91)
==10922==    by 0x401394: run (minishell.c:29)
==10922==    by 0x401394: main (minishell.c:62)
==10922==  Block was alloc'd at
==10922==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==10922==    by 0x40433D: ft_lstnew (ft_lstnew.c:19)
==10922==    by 0x401F32: add_token (lexer.c:59)
==10922==    by 0x401F32: lex_token (lexer.c:113)
==10922==    by 0x401F32: lex (lexer.c:128)
==10922==    by 0x401387: run (minishell.c:27)
==10922==    by 0x401387: main (minishell.c:62)
```

2023-05-09 17:21 UTC, iijung commented on src/minishell.c
> -	ft_lstclear(&tokens, free);
이 부분이 제거되고 파서에서 처리하면서 정리되지 않은 메모리 누수가 발생

```shell
==10922==
==10922== HEAP SUMMARY:
==10922==     in use at exit: 200,193 bytes in 340 blocks
==10922==   total heap usage: 756 allocs, 416 frees, 228,793 bytes allocated
==10922==
==10922== 80 (32 direct, 48 indirect) bytes in 2 blocks are definitely lost in loss record 22 of 60
==10922==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==10922==    by 0x40433D: ft_lstnew (ft_lstnew.c:19)
==10922==    by 0x401EFE: add_token (lexer.c:59)
==10922==    by 0x401EFE: lex_token (lexer.c:117)
==10922==    by 0x401EFE: lex (lexer.c:128)
==10922==    by 0x401387: run (minishell.c:27)
==10922==    by 0x401387: main (minishell.c:62)
==10922==
==10922== 3,830 (496 direct, 3,334 indirect) bytes in 1 blocks are definitely lost in loss record 41 of 60
==10922==    at 0x483B7F3: malloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==10922==    by 0x403F72: ft_calloc (ft_calloc.c:20)
==10922==    by 0x401993: env_load (env_init.c:85)
==10922==    by 0x40132D: main (minishell.c:55)
==10922==
==10922== LEAK SUMMARY:
==10922==    definitely lost: 528 bytes in 3 blocks
==10922==    indirectly lost: 3,382 bytes in 118 blocks
==10922==      possibly lost: 0 bytes in 0 blocks
==10922==    still reachable: 196,283 bytes in 219 blocks
==10922==         suppressed: 0 bytes in 0 blocks
```

아래와 같은 방법으로 파서와 렉서의 역할을 분리해서 처리하면 쉽게 해결될 것 같습니다 
1. parser는 파서가 사용하는 부분만 해제
2. parser가 끝난 후 lexer를 정리하는 ft_lstclear(&tokens, free)를 호출
```c
// psudo code 
lexeme = lex(...);
if (lexeme)
{
    trees = parse(lexeme, ..);
    if (trees)
    {
        execute(trees); 
        clear_parse(trees);
    }
   ft_lstclear(&lexeme, free);
}

```

2023-05-09 17:21 UTC, iijung commented on src/lexer/lexer.h
> +typedef enum e_lexeme			t_e_lexeme;
typedef가 너무 많아져서 t_lex, t_lexeme을 사용하면서 헷갈릴 것 같습니다. 

아래와 같이 변경하는 게 어떤지 제안해봅니다. 
- t_list => t_lst_lex
- s_lexeme => t_s_lex
- e_lexeme => t_e_lex

2023-05-09 17:23 UTC, iijung commented on src/parse/parse.c
> +	printf("debug\n");
debug_print_parse_tree 함수를 주석처리하면 되는 거였네요

2023-05-09 17:27 UTC, iijung commented
클러스터 내에서 valgrind 사용하고 싶으시다면 아래와 같이 사용하시면 됩니다. 

# 도커 설치
```
mkdir -p ~/goinfre/docker
rm -rf ~/Library/Containers/com.docker.docker
ln -s ~/goinfre/docker ~/Library/Containers/com.docker.docker
alias docker-pwd='docker run -it --rm --init -v "$PWD:/pwd" --cap-add SYS_PTRACE nloomans/codam sh -c "cd /pwd; bash"' >> ~/.zshrc
# -cap-add SYS_PTRACE : 도커에서 leak sanitizer 실행이 안되서 해결을 위해 넣음
```

# 도커 실행
```
docker-pwd
docker run -it --rm --init -v "$PWD:/pwd" nloomans/codam sh -c "cd /pwd; bash"'
```

# valgrind 주요 옵션
```
valgrind --leak-check=full --trace-children=yes --track-origins=yes ./minishell 
```

2023-05-10 05:54 UTC, CodyKat commented on src/minishell.c
> -	ft_lstclear(&tokens, free);
지금 구현은 parse_tree 노드가 lex 토큰들을 가지고 있는 구조라 외부에서 lex 토큰 리스트를 한꺼번에 지울 수는 없을 것 같아요.
어떤 메모리들이 정리안되고 있는지 확인해볼게요

2023-05-10 05:55 UTC, CodyKat commented on src/lexer/lexer.h
> +typedef enum e_lexeme			t_e_lexeme;
좋습니다!

2023-05-10 07:28 UTC, iijung commented on src/minishell.c
> -	ft_lstclear(&tokens, free);
앗 아뇨! lex 토큰은 계속 가져가도 돼요! 
파서에서 생성한 데이터만 파서에서 정리한 후 그 후에 렉서를 정리하면 파서에서는 문제없어요!

2023-05-10 15:43 UTC, iijung commented on src/parse/parse_subshell.c
> +		*tmp_node = (*tmp_node)->next;
**테스트 결과** : 성공

```shell
minishell$ ls | ls | echo hi | test && (<< END cat)
debug
DEBUG:: lexeme [4:          AND] len[2] data[&&]
debug
DEBUG:: lexeme [0:       STRING] len[2] data[ls]
DEBUG:: lexeme [2:          IFS] len[1] data[ ]
DEBUG:: lexeme [9:         PIPE] len[1] data[|]
DEBUG:: lexeme [2:          IFS] len[1] data[ ]
DEBUG:: lexeme [0:       STRING] len[2] data[ls]
DEBUG:: lexeme [2:          IFS] len[1] data[ ]
DEBUG:: lexeme [9:         PIPE] len[1] data[|]
DEBUG:: lexeme [2:          IFS] len[1] data[ ]
DEBUG:: lexeme [0:       STRING] len[4] data[echo]
DEBUG:: lexeme [2:          IFS] len[1] data[ ]
DEBUG:: lexeme [0:       STRING] len[2] data[hi]
DEBUG:: lexeme [2:          IFS] len[1] data[ ]
DEBUG:: lexeme [9:         PIPE] len[1] data[|]
DEBUG:: lexeme [2:          IFS] len[1] data[ ]
DEBUG:: lexeme [0:       STRING] len[4] data[test]
DEBUG:: lexeme [2:          IFS] len[1] data[ ]
debug
DEBUG:: lexeme [2:          IFS] len[1] data[ ]
DEBUG:: lexeme [e: PARENTHESIS_OPEN] len[1] data[(]
DEBUG:: lexeme [5:      HEREDOC] len[2] data[<<]
DEBUG:: lexeme [2:          IFS] len[1] data[ ]
DEBUG:: lexeme [0:       STRING] len[3] data[END]
DEBUG:: lexeme [2:          IFS] len[1] data[ ]
DEBUG:: lexeme [0:       STRING] len[3] data[cat]
DEBUG:: lexeme [f: PARENTHESIS_CLOSE] len[1] data[)]
minishell$ exit
==1280==
==1280== HEAP SUMMARY:
==1280==     in use at exit: 199,934 bytes in 323 blocks
==1280==   total heap usage: 599 allocs, 276 frees, 226,064 bytes allocated
==1280==
==1280== LEAK SUMMARY:
==1280==    definitely lost: 0 bytes in 0 blocks
==1280==    indirectly lost: 0 bytes in 0 blocks
==1280==      possibly lost: 0 bytes in 0 blocks
==1280==    still reachable: 199,934 bytes in 323 blocks
==1280==         suppressed: 0 bytes in 0 blocks
==1280== Reachable blocks (those to which a pointer was found) are not shown.
==1280== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==1280==
==1280== For lists of detected and suppressed errors, rerun with: -s
==1280== ERROR SUMMARY: 0 errors from 0 contexts (suppressed: 0 from 0)
```

2023-05-10 15:56 UTC, iijung commented on src/minishell.c
> -	ft_lstclear(&tokens, free);
**테스트 결과** : 실패

```shell
minishell$ '
minishell: lexing error
==1501== Invalid read of size 8
==1501==    at 0x40480B: get_type_operator (parse_operator.c:40)
==1501==    by 0x404871: get_operator (parse_operator.c:50)
==1501==    by 0x4048EC: split_with_operator (parse_operator.c:66)
==1501==    by 0x4045FA: parse (parse.c:91)
==1501==    by 0x4013B5: run (minishell.c:29)
==1501==    by 0x40136F: main (minishell.c:62)
==1501==  Address 0x0 is not stack'd, malloc'd or (recently) free'd
==1501==
==1501==
==1501== Process terminating with default action of signal 11 (SIGSEGV)
==1501==  Access not within mapped region at address 0x0
==1501==    at 0x40480B: get_type_operator (parse_operator.c:40)
==1501==    by 0x404871: get_operator (parse_operator.c:50)
==1501==    by 0x4048EC: split_with_operator (parse_operator.c:66)
==1501==    by 0x4045FA: parse (parse.c:91)
==1501==    by 0x4013B5: run (minishell.c:29)
==1501==    by 0x40136F: main (minishell.c:62)
==1501==  If you believe this happened as a result of a stack
==1501==  overflow in your program's main thread (unlikely but
==1501==  possible), you can try to increase the size of the
==1501==  main thread stack using the --main-stacksize= flag.
==1501==  The main thread stack size used in this run was 8388608.
==1501==
==1501== HEAP SUMMARY:
==1501==     in use at exit: 199,897 bytes in 324 blocks
==1501==   total heap usage: 517 allocs, 193 frees, 224,387 bytes allocated
==1501==
==1501== LEAK SUMMARY:
==1501==    definitely lost: 0 bytes in 0 blocks
==1501==    indirectly lost: 0 bytes in 0 blocks
==1501==      possibly lost: 0 bytes in 0 blocks
==1501==    still reachable: 199,897 bytes in 324 blocks
==1501==         suppressed: 0 bytes in 0 blocks
==1501== Reachable blocks (those to which a pointer was found) are not shown.
==1501== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==1501==
==1501== For lists of detected and suppressed errors, rerun with: -s
==1501== ERROR SUMMARY: 1 errors from 1 contexts (suppressed: 0 from 0)
Segmentation fault
```

2023-05-10 16:09 UTC, iijung commented on src/minishell.c
> -	ft_lstclear(&tokens, free);
ffd356d 에서 위에서 발생한 메모리 누수 수정했습니다

2023-05-10 16:09 UTC, iijung approved these changes

2023-05-10 16:11 UTC, iijung commented on src/Makefile
> +CFLAGS		= -Wall -Wextra -Werror -MMD -MP -g
CFLAGS 나중에 수정 필요!

2023-05-10 16:12 UTC, merged

2023-05-10 16:16 UTC, iijung commented on lib/libft/Makefile
> +CFLAGS = -Wall -Wextra -Werror -MMD -MP -g
CFLAGS 나중에 수정 필요!

2023-05-10 16:18 UTC, iijung commented
코드 수정하신 거 오류 난 부분만 확인했습니다! 메모리 릭 나는 부분이 있어서 그 부분만 조금 수정했어요!